<?php

namespace AppBundle\Repository;

/**
 * PriceOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
