<?php

namespace AppBundle\Repository;

/**
 * ShopOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
